[[connectors]]
allow_override = ["endpoint", "insert_path", "create_time_field", "tags"]
id = "victorialogs_sink"
type = "victorialogs"

[connectors.params]
endpoint = "http://127.0.0.1:9428"   # Host-exposed VictoriaLogs endpoint
insert_path = "/insert/jsonline"     # VictoriaLogs JSON Lines ingest path
